version: "3.3"

services:
  widget-server-api:
    container_name: widget-server-api
    build: ./server/
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "1337:1337"
    restart: always